REM xcopy "C:\Users\golaniz\Documents\Izik\Java\Projects\SimpleRestClient\target\classes" C:\intellij_out\_classpath\classes\ /Y/R/S
copy .\target\*.jar C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\charsets.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\deploy.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\javaws.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\jce.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\jfr.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\jfxrt.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\jsse.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\management-agent.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\plugin.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\resources.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\rt.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\ext\access-bridge-64.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\ext\dnsns.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\ext\jaccess.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\ext\localedata.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\ext\sunec.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\ext\sunjce_provider.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\ext\sunmscapi.jar" C:\intellij_out\_classpath\ /Y
copy "C:\classpath\jdk\1.7.0_55\win64\jre\lib\ext\zipfs.jar" C:\intellij_out\_classpath\ /Y
copy "C:\Users\golaniz\.m2\repository\org\apache\httpcomponents\httpclient\4.1-alpha1\httpclient-4.1-alpha1.jar" C:\intellij_out\_classpath\ /Y
copy "C:\Users\golaniz\.m2\repository\org\apache\httpcomponents\httpcore\4.1-alpha1\httpcore-4.1-alpha1.jar" C:\intellij_out\_classpath\ /Y
copy "C:\Users\golaniz\.m2\repository\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar" C:\intellij_out\_classpath\ /Y
copy "C:\Users\golaniz\.m2\repository\commons-codec\commons-codec\1.3\commons-codec-1.3.jar" C:\intellij_out\_classpath\ /Y
copy "C:\Users\golaniz\.m2\repository\org\apache\wink\wink-client\1.4\wink-client-1.4.jar" C:\intellij_out\_classpath\ /Y
copy "C:\Users\golaniz\.m2\repository\org\apache\wink\wink-common\1.4\wink-common-1.4.jar" C:\intellij_out\_classpath\ /Y
copy "C:\Users\golaniz\.m2\repository\org\apache\geronimo\specs\geronimo-jaxrs_1.1_spec\1.0\geronimo-jaxrs_1.1_spec-1.0.jar" C:\intellij_out\_classpath\ /Y
copy "C:\Users\golaniz\.m2\repository\org\apache\geronimo\specs\geronimo-annotation_1.1_spec\1.0\geronimo-annotation_1.1_spec-1.0.jar" C:\intellij_out\_classpath\ /Y
copy "C:\Users\golaniz\.m2\repository\org\slf4j\slf4j-api\1.6.1\slf4j-api-1.6.1.jar" C:\intellij_out\_classpath\ /Y
copy "C:\Users\golaniz\.m2\repository\javax\xml\bind\jaxb-api\2.2\jaxb-api-2.2.jar" C:\intellij_out\_classpath\ /Y
copy "C:\Users\golaniz\.m2\repository\javax\xml\stream\stax-api\1.0-2\stax-api-1.0-2.jar" C:\intellij_out\_classpath\ /Y
copy "C:\Users\golaniz\.m2\repository\com\sun\xml\bind\jaxb-impl\2.2.1.1\jaxb-impl-2.2.1.1.jar" C:\intellij_out\_classpath\ /Y
copy "C:\Users\golaniz\.m2\repository\javax\activation\activation\1.1\activation-1.1.jar" C:\intellij_out\_classpath\ /Y
copy "C:\Users\golaniz\.m2\repository\org\mockito\mockito-all\1.9.5\mockito-all-1.9.5.jar" C:\intellij_out\_classpath\ /Y
copy "C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 14.0.2\lib\idea_rt.jar" C:\intellij_out\_classpath\ /Y
